services:
    as-sensors-api:
        build:
            context: .
            dockerfile: ./as-sensors-api/Dockerfile
        ports:
            - "5002:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        restart: on-failure

  